services:
  app:
    build:
      context: ./app
    container_name: fastapi_beer
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/beerdb1"
    volumes:
      - ./app:/app
  db:
    image: postgres:15
    container_name: postgres_beerdb1  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beerdb1
    ports:
      - "5432:5432"
    volumes:
      - beerdb_data:/var/lib/postgresql/data
  django:
    build:
      context: ./front
    container_name: new_django
    depends_on:
      - app
    ports:
      - "8001:8080"
    volumes:
      - ./front:/front

volumes:
  beerdb_data:
